# Generated by Django 3.0.7 on 2022-06-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
